name: VoxelSniper
main: com.voxelplugineering.voxelsniper.VoxelSniperBukkit
version: 7.0.0
website: http://thevoxelbox.com
authors: [gabizou, Deamon5550]
description: The premier long range voxel-based terrain editing tool.